=== jamesfu120/l2town_Custom_Server/L2J_Mobius_Essence_10.1_SamuraiCrow/dist/game/data/xsd/playerTemplate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="classId" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:nonNegativeInteger">
							<xs:minInclusive value="0" />
							<xs:maxInclusive value="263" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="staticData" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence maxOccurs="1" minOccurs="1">
							<xs:element type="xs:nonNegativeInteger" name="baseINT" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseSTR" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseCON" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseMEN" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseDEX" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseWIT" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:integer" name="physicalAbnormalResist" minOccurs="0" maxOccurs="1" />
							<xs:element type="xs:integer" name="magicAbnormalResist" minOccurs="0" maxOccurs="1" />
							<xs:element name="creationPoints" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="0">
										<xs:element name="node" maxOccurs="unbounded" minOccurs="1">
											<xs:complexType>
												<xs:attribute type="xs:integer" name="x" use="required" />
												<xs:attribute type="xs:integer" name="y" use="required" />
												<xs:attribute type="xs:integer" name="z" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="basePAtk" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:positiveInteger" name="baseCritRate" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:positiveInteger" name="baseMCritRate" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:positiveInteger" name="basePSkillCritRate" minOccurs="0" maxOccurs="1" />
							<xs:element name="baseAtkType" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:token">
										<xs:enumeration value="FIST" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="basePAtkSpd" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:positiveInteger" name="baseMAtkSpd" minOccurs="0" maxOccurs="1" />
							<xs:element name="basePDef" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:positiveInteger" name="chest" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="legs" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="head" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="feet" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="gloves" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="underwear" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="cloak" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="baseMAtk" minOccurs="1" maxOccurs="1" />
							<xs:element name="baseMDef" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:positiveInteger" name="rear" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="lear" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="rfinger" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="lfinger" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="neck" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:nonNegativeInteger" name="baseCanPenetrate" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:positiveInteger" name="baseAtkRange" minOccurs="1" maxOccurs="1" />
							<xs:element name="baseDamRange" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:nonNegativeInteger" name="verticalDirection" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:nonNegativeInteger" name="horizontalDirection" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:nonNegativeInteger" name="distance" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:nonNegativeInteger" name="width" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="baseRndDam" minOccurs="1" maxOccurs="1" />
							<xs:element name="baseMoveSpd" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:positiveInteger" name="walk" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="run" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="slowSwim" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="fastSwim" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="baseBreath" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:positiveInteger" name="baseSafeFall" minOccurs="1" maxOccurs="1" />
							<xs:element name="collisionMale" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:decimal" name="radius" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="height" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="collisionFemale" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:decimal" name="radius" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="height" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="lvlUpgainData" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence maxOccurs="1" minOccurs="1">
							<xs:element name="level" minOccurs="99" maxOccurs="99">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:decimal" name="hp" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="mp" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="cp" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="hpRegen" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="mpRegen" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="cpRegen" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
									<xs:attribute name="val" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="107" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== jamesfu120/l2town_Custom_Server/L2J_Mobius_Essence_10.1_SamuraiCrow/dist/game/data/stats/players/templates/Samurai/Ashigaru.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../xsd/playerTemplate.xsd">
	<classId>260</classId>
	<staticData>
		<baseINT>30</baseINT>
		<baseSTR>42</baseSTR>
		<baseCON>44</baseCON>
		<baseMEN>24</baseMEN>
		<baseDEX>20</baseDEX>
		<baseWIT>10</baseWIT>
		<physicalAbnormalResist>15</physicalAbnormalResist>
		<magicAbnormalResist>10</magicAbnormalResist>
		<creationPoints>
			<node x="148746" y="214133" z="-2063" />
		</creationPoints>
		<basePAtk>4</basePAtk>
		<baseCritRate>4</baseCritRate>
		<baseMCritRate>5</baseMCritRate>
		<basePSkillCritRate>5</basePSkillCritRate>
		<baseAtkType>FIST</baseAtkType>
		<basePAtkSpd>300</basePAtkSpd>
		<baseMAtkSpd>333</baseMAtkSpd>
		<basePDef>
			<chest>31</chest>
			<legs>18</legs>
			<head>12</head>
			<feet>7</feet>
			<gloves>8</gloves>
			<underwear>3</underwear>
			<cloak>1</cloak>
		</basePDef>
		<baseMAtk>6</baseMAtk>
		<baseMDef>
			<rear>9</rear>
			<lear>9</lear>
			<rfinger>5</rfinger>
			<lfinger>5</lfinger>
			<neck>13</neck>
		</baseMDef>
		<baseCanPenetrate>0</baseCanPenetrate>
		<baseAtkRange>20</baseAtkRange>
		<baseDamRange>
			<verticalDirection>0</verticalDirection>
			<horizontalDirection>0</horizontalDirection>
			<distance>26</distance>
			<width>120</width>
		</baseDamRange>
		<baseRndDam>10</baseRndDam>
		<baseMoveSpd>
			<walk>87</walk>
			<run>140</run>
			<slowSwim>50</slowSwim>
			<fastSwim>50</fastSwim>
		</baseMoveSpd>
		<baseBreath>100</baseBreath>
		<baseSafeFall>500</baseSafeFall>
		<collisionMale>
			<radius>9</radius>
			<height>23</height>
		</collisionMale>
		<collisionFemale>
			<radius>8</radius>
			<height>23.5</height>
		</collisionFemale>
	</staticData>
	<lvlUpgainData>
		<level val="1">
			<hp>97</hp>
			<mp>40</mp>
			<cp>48.5</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2</cpRegen>
		</level>
		<level val="2">
			<hp>115.2</hp>
			<mp>47.28</mp>
			<cp>57.6</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2</cpRegen>
		</level>
		<level val="3">
			<hp>133.6</hp>
			<mp>54.64</mp>
			<cp>66.8</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2</cpRegen>
		</level>
		<level val="4">
			<hp>152.2</hp>
			<mp>62.08</mp>
			<cp>76.1</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2</cpRegen>
		</level>
		<level val="5">
			<hp>171</hp>
			<mp>69.6</mp>
			<cp>85.5</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2</cpRegen>
		</level>
		<level val="6">
			<hp>190</hp>
			<mp>77.2</mp>
			<cp>95</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2</cpRegen>
		</level>
		<level val="7">
			<hp>209.2</hp>
			<mp>84.88</mp>
			<cp>104.6</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2</cpRegen>
		</level>
		<level val="8">
			<hp>228.6</hp>
			<mp>92.64</mp>
			<cp>114.3</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2</cpRegen>
		</level>
		<level val="9">
			<hp>248.2</hp>
			<mp>100.48</mp>
			<cp>124.1</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2</cpRegen>
		</level>
		<level val="10">
			<hp>268</hp>
			<mp>108.4</mp>
			<cp>134</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2</cpRegen>
		</level>
		<level val="11">
			<hp>288</hp>
			<mp>116.4</mp>
			<cp>144</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="12">
			<hp>308.2</hp>
			<mp>124.48</mp>
			<cp>154.1</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="13">
			<hp>328.6</hp>
			<mp>132.64</mp>
			<cp>164.3</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="14">
			<hp>349.2</hp>
			<mp>140.88</mp>
			<cp>174.6</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="15">
			<hp>370</hp>
			<mp>149.2</mp>
			<cp>185</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="16">
			<hp>391</hp>
			<mp>157.6</mp>
			<cp>195.5</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="17">
			<hp>412.2</hp>
			<mp>166.08</mp>
			<cp>206.1</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="18">
			<hp>433.6</hp>
			<mp>174.64</mp>
			<cp>216.8</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="19">
			<hp>455.2</hp>
			<mp>183.28</mp>
			<cp>227.6</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="20">
			<hp>477</hp>
			<mp>192</mp>
			<cp>238.5</cp>
			<hpRegen>2</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="21">
			<hp>499</hp>
			<mp>200.8</mp>
			<cp>249.5</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="22">
			<hp>521.2</hp>
			<mp>209.68</mp>
			<cp>260.6</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="23">
			<hp>543.6</hp>
			<mp>218.64</mp>
			<cp>271.8</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="24">
			<hp>566.2</hp>
			<mp>227.68</mp>
			<cp>283.1</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="25">
			<hp>589</hp>
			<mp>236.8</mp>
			<cp>294.5</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="26">
			<hp>612</hp>
			<mp>246</mp>
			<cp>306</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="27">
			<hp>635.2</hp>
			<mp>255.28</mp>
			<cp>317.6</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="28">
			<hp>658.6</hp>
			<mp>264.64</mp>
			<cp>329.3</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="29">
			<hp>682.2</hp>
			<mp>274.08</mp>
			<cp>341.1</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="30">
			<hp>706</hp>
			<mp>283.6</mp>
			<cp>353</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="31">
			<hp>730</hp>
			<mp>293.2</mp>
			<cp>365</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="32">
			<hp>754.2</hp>
			<mp>302.88</mp>
			<cp>377.1</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="33">
			<hp>778.6</hp>
			<mp>312.64</mp>
			<cp>389.3</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="34">
			<hp>803.2</hp>
			<mp>322.48</mp>
			<cp>401.6</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="35">
			<hp>828</hp>
			<mp>332.4</mp>
			<cp>414</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="36">
			<hp>853</hp>
			<mp>342.4</mp>
			<cp>426.5</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="37">
			<hp>878.2</hp>
			<mp>352.48</mp>
			<cp>439.1</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="38">
			<hp>903.6</hp>
			<mp>362.64</mp>
			<cp>451.8</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="39">
			<hp>929.2</hp>
			<mp>372.88</mp>
			<cp>464.6</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="40">
			<hp>955</hp>
			<mp>383.2</mp>
			<cp>477.5</cp>
			<hpRegen>3</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="41">
			<hp>981</hp>
			<mp>393.6</mp>
			<cp>490.5</cp>
			<hpRegen>4</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="42">
			<hp>1007.2</hp>
			<mp>404.08</mp>
			<cp>503.6</cp>
			<hpRegen>4</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="43">
			<hp>1033.6</hp>
			<mp>414.64</mp>
			<cp>516.8</cp>
			<hpRegen>4</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="44">
			<hp>1060.2</hp>
			<mp>425.28</mp>
			<cp>530.1</cp>
			<hpRegen>4</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="45">
			<hp>1087</hp>
			<mp>436</mp>
			<cp>543.5</cp>
			<hpRegen>4</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="46">
			<hp>1114</hp>
			<mp>446.8</mp>
			<cp>557</cp>
			<hpRegen>4</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="47">
			<hp>1141.2</hp>
			<mp>457.68</mp>
			<cp>570.6</cp>
			<hpRegen>4</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="48">
			<hp>1168.6</hp>
			<mp>468.64</mp>
			<cp>584.3</cp>
			<hpRegen>4</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="49">
			<hp>1196.2</hp>
			<mp>479.68</mp>
			<cp>598.1</cp>
			<hpRegen>4</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="50">
			<hp>1224</hp>
			<mp>490.8</mp>
			<cp>612</cp>
			<hpRegen>4</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="51">
			<hp>1252</hp>
			<mp>502</mp>
			<cp>626</cp>
			<hpRegen>4</hpRegen>
			<mpRegen>2.4</mpRegen>
			<cpRegen>6.5</cpRegen>
		</level>
		<level val="52">
			<hp>1280.2</hp>
			<mp>513.28</mp>
			<cp>640.1</cp>
			<hpRegen>4</hpRegen>
			<mpRegen>2.4</mpRegen>
